import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import JSZip from "jszip";

// A small, spec-valid 8x8 PNG (generated by canvas.toBlob) inlined so the suite
// needs no binary fixture. It must be decodable by createImageBitmap, which is
// stricter than the legacy <img> decoder.
const PNG_8x8_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAI0lEQVR4AdzKMQ0AAAwCwQZbdVfRXcEB7Hzy22Hv6caEOoAAAAD//8+/PiYAAAAGSURBVAMA2TQVoVg4pVsAAAAASUVORK5CYII=";

const pngFile = (name = "photo.png") => ({
  name,
  mimeType: "image/png",
  buffer: Buffer.from(PNG_8x8_BASE64, "base64"),
});

/**
 * File signatures ("magic bytes"). A correct extension is worthless if the
 * bytes underneath disagree, which is exactly the failure these tests exist
 * to catch.
 */
const SIGNATURES = {
  png: (b) =>
    b
      .subarray(0, 8)
      .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
  jpeg: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff,
  webp: (b) =>
    b.subarray(0, 4).toString("latin1") === "RIFF" &&
    b.subarray(8, 12).toString("latin1") === "WEBP",
};

const describeBytes = (b) =>
  [...b.subarray(0, 12)].map((x) => x.toString(16).padStart(2, "0")).join(" ");

/** Downloads the prepared ZIP and returns its parsed entries. */
const downloadZip = async (page) => {
  await expect(page.locator("#downloadZipBtn")).toBeEnabled();

  const downloadPromise = page.waitForEvent("download");
  await page.locator("#downloadZipBtn").click();
  const download = await downloadPromise;

  expect(download.suggestedFilename()).toBe("converted-images.zip");

  const zip = await JSZip.loadAsync(await readFile(await download.path()));
  return { zip, names: Object.keys(zip.files) };
};

const addImageAndConvert = async (page, format) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();
  if (format) {
    await page.locator("#formatSelect").selectOption(format);
  }
  await page.locator("#convertBtn").click();
};

test.beforeEach(async ({ page }) => {
  await page.goto("/");
});

/* ------------------------------------------------------------------ *
 * Upload / preview
 * ------------------------------------------------------------------ */

test("uploading an image shows a preview and hides the placeholder", async ({
  page,
}) => {
  await expect(page.locator("#previewPlaceholder")).toBeVisible();

  await page.locator("#fileInput").setInputFiles(pngFile());

  await expect(page.locator("#previewGrid > div")).toHaveCount(1);
  await expect(page.locator("#previewPlaceholder")).toBeHidden();
});

test("running the convert pipeline enables the ZIP download", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();

  await expect(page.locator("#downloadZipBtn")).toBeDisabled();
  await page.locator("#convertBtn").click();

  await expect(page.locator("#successAlert")).toBeVisible();
  await expect(page.locator("#downloadZipBtn")).toBeEnabled();
});

/* ------------------------------------------------------------------ *
 * Magic-byte validation of the actual ZIP payload
 * ------------------------------------------------------------------ */

test("PNG output is named .png AND carries a real PNG signature", async ({
  page,
}) => {
  await addImageAndConvert(page, "png");
  const { zip, names } = await downloadZip(page);

  expect(names).toEqual(["photo.png"]);

  const bytes = await zip.file("photo.png").async("nodebuffer");
  expect(
    SIGNATURES.png(bytes),
    `expected PNG signature, got: ${describeBytes(bytes)}`,
  ).toBe(true);
});

test("JPG output is named .jpg AND carries a real JPEG signature", async ({
  page,
}) => {
  await addImageAndConvert(page, "jpg");
  const { zip, names } = await downloadZip(page);

  expect(names).toEqual(["photo.jpg"]);

  const bytes = await zip.file("photo.jpg").async("nodebuffer");
  expect(
    SIGNATURES.jpeg(bytes),
    `expected JPEG signature, got: ${describeBytes(bytes)}`,
  ).toBe(true);
});

test("WEBP output is named .webp AND carries a real WEBP signature", async ({
  page,
}) => {
  await addImageAndConvert(page, "webp");
  const { zip, names } = await downloadZip(page);

  expect(names).toEqual(["photo.webp"]);

  const bytes = await zip.file("photo.webp").async("nodebuffer");
  expect(
    SIGNATURES.webp(bytes),
    `expected WEBP signature, got: ${describeBytes(bytes)}`,
  ).toBe(true);
});

/* ------------------------------------------------------------------ *
 * Capability detection: unencodable formats never reach the menu
 * ------------------------------------------------------------------ */

test("formats the browser cannot encode are removed from the menu", async ({
  page,
}) => {
  // Chromium substitutes PNG for AVIF, so the probe must drop it — while
  // leaving every format it can genuinely encode in place.
  await expect(page.locator("#formatSelect option")).toHaveCount(3);

  const values = await page
    .locator("#formatSelect option")
    .evaluateAll((options) => options.map((o) => o.value));

  expect(values).toEqual(["jpg", "png", "webp"]);
  expect(values).not.toContain("avif");
});

test("the selected format always falls back to an encodable one", async ({
  page,
}) => {
  // Whatever survives detection, the menu must never be left empty or
  // sitting on an option that was removed.
  const selected = await page.locator("#formatSelect").inputValue();
  expect(["jpg", "png", "webp"]).toContain(selected);
});

/* ------------------------------------------------------------------ *
 * Modes
 * ------------------------------------------------------------------ */

test("resize + convert mode produces a file with a valid signature", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();

  await page.locator('[data-mode="both"]').click();
  await page.locator("#resizeWidth").fill("50");
  await page.locator("#formatSelect").selectOption("png");
  await page.locator("#convertBtn").click();

  await expect(page.locator("#successAlert")).toBeVisible();
  const { zip, names } = await downloadZip(page);

  expect(names).toEqual(["photo.png"]);
  const bytes = await zip.file("photo.png").async("nodebuffer");
  expect(SIGNATURES.png(bytes)).toBe(true);
});

test("resize-only mode keeps the actions reachable and preserves the format", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();

  await page.locator('[data-mode="resize"]').click();

  // The convert panel steps aside in this mode, but the actions must not go
  // with it: they used to live inside that panel, which left resize-only with
  // no way to start a batch at all.
  await expect(page.locator("#convertControls")).toBeHidden();
  await expect(page.locator("#convertBtn")).toBeVisible();
  await expect(page.locator("#convertBtn")).toBeEnabled();

  await page.locator("#resizeWidth").fill("1");
  await page.locator("#convertBtn").click();

  const { names, zip } = await downloadZip(page);
  expect(names).toEqual(["photo.png"]);

  // Resize-only keeps the original format, so the bytes must still be a PNG.
  const bytes = await zip.file(names[0]).async("nodebuffer");
  expect(
    SIGNATURES.png(bytes),
    `expected PNG bytes, got: ${describeBytes(bytes)}`,
  ).toBe(true);
});

test("the actions stay reachable in every mode", async ({ page }) => {
  for (const mode of ["convert", "resize", "both"]) {
    await page.locator(`[data-mode="${mode}"]`).click();

    await expect(
      page.locator("#convertBtn"),
      `Run Pipeline must be visible in "${mode}" mode`,
    ).toBeVisible();
    await expect(
      page.locator("#downloadZipBtn"),
      `Download must be visible in "${mode}" mode`,
    ).toBeVisible();
  }
});

test("an over-limit resize is clamped, not hung, and still downloads", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();

  await page.locator('[data-mode="both"]').click();
  await page.locator("#formatSelect").selectOption("png");

  // The input now carries max="4096"; bypass native validation by setting the
  // value directly and dispatching the input event the app listens for. This
  // proves the JS engine — not just the HTML — clamps the dimension.
  await page.locator("#resizeWidth").evaluate((el) => {
    el.value = "20000";
    el.dispatchEvent(new Event("input", { bubbles: true }));
  });

  await page.locator("#convertBtn").click();

  // The whole point: the batch finishes (no OOM hang) and the ZIP is ready.
  await expect(page.locator("#downloadZipBtn")).toBeEnabled({ timeout: 15000 });
  const { zip, names } = await downloadZip(page);
  expect(names).toEqual(["photo.png"]);

  const bytes = await zip.file("photo.png").async("nodebuffer");
  expect(SIGNATURES.png(bytes)).toBe(true);

  // PNG IHDR: width @ byte 16, height @ byte 20 (big-endian). Both must have
  // been clamped to the 4096 ceiling rather than allocated at 20000.
  const width = bytes.readUInt32BE(16);
  const height = bytes.readUInt32BE(20);
  expect(width).toBeLessThanOrEqual(4096);
  expect(height).toBeLessThanOrEqual(4096);
  expect(width).toBeGreaterThan(2);
});

test("a partial batch zips only the successes and reports the shortfall", async ({
  page,
}) => {
  const good = pngFile("ok.png");
  // A file that passes the image/* MIME filter but cannot be decoded, so the
  // engine skips it via onFileError without failing the whole batch.
  const bad = {
    name: "broken.png",
    mimeType: "image/png",
    buffer: Buffer.from("this is not a real image"),
  };

  await page.locator("#fileInput").setInputFiles([good, bad]);
  await expect(page.locator("#previewGrid > div")).toHaveCount(2);

  await page.locator("#formatSelect").selectOption("png");
  await page.locator("#convertBtn").click();

  await expect(page.locator("#downloadZipBtn")).toBeEnabled();
  await expect(page.locator("#statusText")).toContainText("Processed 1 of 2");

  const { names } = await downloadZip(page);
  expect(names).toEqual(["ok.png"]); // only the decodable file is archived
});

test("deleting an image uses a two-click inline confirm (no dialog)", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await expect(page.locator("#previewGrid > div")).toHaveCount(1);

  const deleteBtn = page.locator('[data-role="delete-image"]').first();

  // First click arms (button becomes a check); the tile is NOT yet removed.
  await deleteBtn.click();
  await expect(deleteBtn).toHaveText("✓");
  await expect(page.locator("#previewGrid > div")).toHaveCount(1);

  // Second click confirms.
  await deleteBtn.click();
  await expect(page.locator("#previewGrid > div")).toHaveCount(0);
  await expect(page.locator("#previewPlaceholder")).toBeVisible();
});

test("delete controls are locked while a batch is processing", async ({
  page,
}) => {
  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();

  await page.locator("#convertBtn").click();

  // By the time the ZIP is ready the batch has finished, so delete is usable
  // again — the durable, non-flaky assertion of the lock's release.
  await expect(page.locator("#downloadZipBtn")).toBeEnabled();
  await expect(
    page.locator('[data-role="delete-image"]').first(),
  ).toBeEnabled();
  await expect(
    page.locator('[data-role="delete-image"]').first(),
  ).toHaveAttribute("aria-disabled", "false");
});

test("the mode switch is a radio group with arrow-key navigation", async ({
  page,
}) => {
  const convertTab = page.locator('[data-mode="convert"]');
  const resizeTab = page.locator('[data-mode="resize"]');

  await expect(page.locator("#modeTabs")).toHaveAttribute(
    "role",
    "radiogroup",
  );
  await expect(convertTab).toHaveAttribute("role", "radio");

  await convertTab.focus();
  await expect(convertTab).toHaveAttribute("aria-checked", "true");

  await page.keyboard.press("ArrowRight");

  await expect(resizeTab).toBeFocused();
  await expect(resizeTab).toHaveAttribute("aria-checked", "true");
  await expect(convertTab).toHaveAttribute("aria-checked", "false");

  // Roving tabindex: the group is a single stop in the Tab order.
  await expect(resizeTab).toHaveAttribute("tabindex", "0");
  await expect(convertTab).toHaveAttribute("tabindex", "-1");
});

test("the aspect lock is a named toggle whose knob follows its state", async ({
  page,
}) => {
  await page.locator('[data-mode="resize"]').click();

  const toggle = page.locator("#lockAspect");
  const knob = toggle.locator("span");

  await expect(toggle).toHaveAttribute("aria-pressed", "true");
  await expect(toggle).toHaveAttribute("aria-labelledby", "lockAspectLabel");

  const offsetWhenOn = await knob.evaluate(
    (el) => el.getBoundingClientRect().left,
  );

  await toggle.click();

  await expect(toggle).toHaveAttribute("aria-pressed", "false");
  // The knob previously carried an unconditional translate, so it never moved.
  await expect
    .poll(() => knob.evaluate((el) => el.getBoundingClientRect().left))
    .toBeLessThan(offsetWhenOn);
});

/* ------------------------------------------------------------------ *
 * PWA — installable + offline (Phase B)
 * ------------------------------------------------------------------ */

test("exposes a valid, installable web app manifest", async ({ page }) => {
  await page.goto("/");

  const href = await page.locator('link[rel="manifest"]').getAttribute("href");
  expect(href).toBeTruthy();

  const res = await page.request.get(href);
  expect(res.ok()).toBe(true);

  const manifest = await res.json();
  expect(manifest.name).toBe("Glass Image Processor");
  expect(manifest.display).toBe("standalone");
  // At least a 192 and a 512 icon are required for install prompts.
  const sizes = manifest.icons.map((i) => i.sizes);
  expect(sizes).toContain("192x192");
  expect(sizes).toContain("512x512");
});

test("registers a service worker and still works fully offline", async ({
  page,
  context,
}) => {
  await page.goto("/");

  // Wait for the service worker to activate, then for it to control the page.
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready;
  });
  await page.waitForFunction(
    () => navigator.serviceWorker.controller != null,
    null,
    { timeout: 20_000 },
  );

  // Kill the network and reload — the app shell must come from the SW cache.
  await context.setOffline(true);
  await page.reload();

  await expect(page.locator("#app-title")).toHaveText("Glass Image Processor");
  // The format menu is populated by client-side canvas probing, proving the
  // JS bundle ran offline (not just a cached static shell).
  await expect(page.locator("#formatSelect option").first()).toBeAttached();

  await context.setOffline(false);
});

/* ------------------------------------------------------------------ *
 * Worker pipeline, fallback & hardening (Phases C + D)
 * ------------------------------------------------------------------ */

test("same-named inputs produce distinct ZIP entries (no overwrite)", async ({
  page,
}) => {
  await page
    .locator("#fileInput")
    .setInputFiles([pngFile("dup.png"), pngFile("dup.png")]);
  await expect(page.locator("#previewGrid > div")).toHaveCount(2);

  await page.locator("#formatSelect").selectOption("png");
  await page.locator("#convertBtn").click();

  const { names } = await downloadZip(page);
  expect(names.sort()).toEqual(["dup-2.png", "dup.png"]);
});

test("falls back to main-thread processing without OffscreenCanvas", async ({
  page,
}) => {
  // Hide OffscreenCanvas before any app code runs, forcing the inline path.
  await page.addInitScript(() => {
    window.OffscreenCanvas = undefined;
  });
  await page.goto("/");

  await page.locator("#fileInput").setInputFiles(pngFile());
  await page.locator("#previewGrid > div").first().waitFor();
  await page.locator("#formatSelect").selectOption("png");
  await page.locator("#convertBtn").click();

  await expect(page.locator("#downloadZipBtn")).toBeEnabled();
  const { zip, names } = await downloadZip(page);
  expect(names).toEqual(["photo.png"]);
  const bytes = await zip.file("photo.png").async("nodebuffer");
  expect(SIGNATURES.png(bytes)).toBe(true);
});

test("rejects SVG files (raster pipeline only)", async ({ page }) => {
  await page.locator("#fileInput").setInputFiles({
    name: "vector.svg",
    mimeType: "image/svg+xml",
    buffer: Buffer.from(
      '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"></svg>',
    ),
  });

  await expect(page.locator("#previewGrid > div")).toHaveCount(0);
  await expect(page.locator("#errorAlert")).toBeVisible();
});
